'use strict';(function(h){function f(a,b,c,d){void 0===b&&(b=0);if(!a||null===a.tabIndex||"none"===a.tabIndex||-1===a.tabIndex)return d?null:-1;var e=h.jL.isUndefined(a.tabIndex);c=f(c);a=k(a)||e&&a.description?(-1<c?c:0)+b:e?-1:a.tabIndex;return-1<a||!d?a:null}function k(a){return"auto"==a.tabIndex||"auto"==a.tabindex}function n(a,b){b.elGetter(a)&&(b.parentGetter(a).currentOptions.useTabNavigation?p(a,b):l(a,b))}function p(a,b,c){var d=a.chart.currentOptions,e=b.elGetter(a),g=a.currentOptions,h=
g.description||k(g)&&"%name";e.attr({role:h?b.role:null,tabindex:c?-1:f(g,b.tabIndex,d),"aria-label":h?b.tokenizer(a,h):null});t(a,b);b.postSubscriptionApplier&&b.postSubscriptionApplier(a)}function t(a,b){if(!a.vkeyenterHandler){var c=b.elGetter(a),d=b.parentGetter(a);a.vkeyenterHandler=c.on("vkeyenter",function(c){return b.clickFn(a,c)});a.vchangefocusHandler=c.on("vchangefocus",function(c){b.focusFn(a,c);d.focusedItem=c.hasFocus?a:null;!c.hasFocus&&b.isParentNavigatable&&b.isParentNavigatable(d)&&
b.elGetter(a).attr({tabindex:-1})})}}function l(a,b){var c=b.parentGetter(a);if(!c.keysNavigationApplied){var d=b.isParentNavigatable&&b.isParentNavigatable(c);a.activeNavigationItem=!d;u(c,b,d);c.keysNavigationApplied=!0}p(a,b,!a.activeNavigationItem)}function u(a,b,c){if(!a.keyupDocumentEvent){var d=a.chart.renderer.renderer.documentElement;c&&(a.vchangefocusHandler=b.parentElGetter(a).on("vchangefocus",function(b){a.parentFocused=b.eventArgs.hasFocus?a:null}));a.keydownDocumentEvent=d.on("keydown",
function(b){(a.focusedItem||a.parentFocused)&&h.jL.isSuitableKey(b)&&b.preventDefault()});a.keyupDocumentEvent=d.on("keyup",function(c){var d=a.parentFocused,e=a.focusedItem;if((e||d)&&h.jL.isSuitableKey(c)){var f=b.childrenGetter(a),m=f.length;d=d?-1:f.indexOf(e);c=c.keyCode;if(m){if(c===h.jL.KeyCode.Down||c===h.jL.KeyCode.Right)var q=d===m-1?0:d+1;if(c===h.jL.KeyCode.Up||c===h.jL.KeyCode.Left)q=1>d?m-1:d-1;f=f[q];f.activeNavigationItem=!0;e&&(e.activeNavigationItem=!1,l(e,b));l(f,b);b.elGetter(f).el.focus()}}})}}
function v(a){var b=a.currentOptions,c=f(b);(h.jL.evalPath(a,"currentOptions.description")||-1<c||k(b))&&a.flowEvents.optionsApplied.on(w)}function w(a){r[a.type]&&r[a.type](a.owner)}var x={isParentNavigatable:function(a){return a.isVisible&&-1<f(a.currentOptions,50,a.chart.currentOptions)},parentGetter:function(a){return a.legend},childrenGetter:function(a){return a.items},elGetter:function(a){return a.trackerElement},role:"menuitem",tabIndex:55,parentTabIndex:50,parentElGetter:function(a){return a.rootPanel},
tokenizer:function(a,b){return a.target.replaceTokens(b)},clickFn:function(a,b){return a.click(b)},focusFn:function(a,b){b.hasFocus?a.mouseover(b):a.mouseout(b)}},y={parentGetter:function(a){return a.series},childrenGetter:function(a){return a._points},elGetter:function(a){return a.visuals.body},role:"presentation",tabIndex:90,tokenizer:function(a,b){return a.replaceTokens(b)},clickFn:function(a,b){return a.series.visualizer.pointClick(b,a)},focusFn:function(a,b){var c=a.series;b.hasFocus?c.visualizer.pointMouseOver(b,
a):c.visualizer.pointMouseOut(b,a)},postSubscriptionApplier:function(a){var b=a.visuals.label;b&&b.attr({"aria-hidden":a.currentOptions.description?"true":null})}},r={chart:function(a){var b=a.currentOptions,c=a.renderer.renderer.root,d=b.description||k(b)&&"%title";c.attr({role:d?"presentation":null,tabindex:f(b,20,b,!0),"aria-label":d?a.replaceTokens(d):null})},chartArea:function(a){var b=a.currentOptions,c=b.description;a.rootPanel.attr({role:c?"region":null,tabindex:f(b,40,a.chart.currentOptions,
!0),"aria-label":c?a.replaceTokens(c):null})},title:function(a){var b=a.target.chart,c=b.currentOptions,d=a.currentOptions,e=d.description||k(d)&&"%name",g=a.rootVisuals.content;a.rootPanel.attr({role:e?"heading":null,tabindex:f(d,30,c,!0),"aria-label":e?b.replaceTokens(e):null});g.attr({"aria-hidden":e?"true":null})},legend:function(a){var b=a.chart,c=b.currentOptions,d=a.currentOptions,e=a.isVisible&&d.description;a.rootPanel.attr({role:e?"menu":null,tabindex:a.isVisible?f(d,50,c,!0):null,"aria-label":e?
b.replaceTokens(e):null});a.rootVisuals.stack.attr({"aria-hidden":e?"true":null})},legendEntry:function(a){n(a,x)},series:function(a){var b=a.chart.currentOptions,c=a.currentOptions,d=c.description||k(c)&&"%name",e=a.rootVisuals.area;e&&e.attr({role:d?"group":null,tabindex:f(c,80,b,!0),"aria-label":d?a.replaceTokens(d):null})},point:function(a){n(a,y)},toolbar:function(a){var b=a.chart.currentOptions,c=b.toolbar;-1<f(b)&&(c.tabIndex=h.jL.def(c.tabIndex)?c.tabIndex:"auto");b=f(c,100,b);a.activateAccessibility(-1<
b,b)},axis:function(a){var b=a.chart.currentOptions,c=a.currentOptions,d=c.description,e=a.rootPanel&&a.rootPanel,g=a.rootVisuals&&a.rootVisuals.main;a=a.chartArea&&a.chartArea.replaceTokens?a.chartArea:a.chart;e&&e.attr({role:d?"group":null,tabindex:f(c,60,b,!0),"aria-label":d?a.replaceTokens(d):null});g&&g.attr({"aria-hidden":d?"true":null})},annotation:function(a){var b=a.chart.currentOptions,c=a.currentOptions,d=c.description,e=a.rootPanel&&a.rootPanel,g=a.rootVisuals&&a.rootVisuals.content;a=
a.target||a.chart;e&&e.attr({role:d?"tooltip":null,tabindex:f(c,70,b,!0),"aria-label":d?a.replaceTokens(d):null});g&&g.attr({"aria-hidden":d?"true":null})},uiitem:function(a){var b=a.currentOptions.description,c=a.rootPanel&&a.rootPanel;a=a.target||a.chart;c&&c.attr({role:b?"button":null,"aria-label":b?a.replaceTokens(b):null})},label:function(a){var b=a.chart.currentOptions,c=a.currentOptions,d=c.description,e=a.rootPanel&&a.rootPanel,g=a.rootVisuals&&a.rootVisuals.text;a=a.chart;e&&e.attr({role:d?
"tooltip":null,tabindex:f(c,110,b,!0),"aria-label":d?a.replaceTokens(d):null});g&&g.attr({"aria-hidden":d?"true":null})},grid:function(a){var b=a.currentOptions,c=b.grid;if(c&&!1!==c.enabled){var d=c.description,e=a._grid,g=a._gridSwitch,k=f(c,10,b,!0);if(g){g.attr({role:d?"menu":null,tabindex:d?k:-1,"aria-label":d?a.replaceTokens(d):null});var l=c.buttons||{};h.jL.eachKey(l,function(b){var c=l[b]||{};b=g.buttons[b];var d=c.description;c=c.tabIndex||k+1;b&&b.attr({role:d?"button":null,tabindex:c,
"aria-label":d?a.replaceTokens(d):null})})}e&&(c=(b=h.jL.evalPath(c,"buttons.export"))&&b.description,d=b&&(b.tabIndex||k+2),e=e.exportButton,b&&e&&e.attr({role:c?"button":null,tabindex:d,"aria-label":c?a.replaceTokens(c):null}))}}};h.moduleLoader.registerModule("modules/accessibility")&&(h.chartInitializers.accessibility=v)})(JSC.internal._modules.accessibility.externals);
